### ISSUE TITLE
Download from ntv fails

### ISSUE THREAD

**Issue by probonopd** [isync/www-video-download#1]
Download from ntv fails for all URLs I have tried with messages like this:

```
ntv-downloader.pl http://www.n-tv.de/mediathek/videos/panorama/Autofahrer-lassen-Unfallopfer-einfach-liegen-article14436766.html
WWW::Video::Download: http://www.n-tv.de/mediathek/videos/panorama/Autofahrer-lassen-Unfallopfer-einfach-liegen-article14436766.html 
Could not extract playlist URL at ntv-downloader.pl line 95.
```

**Comment by isync** [comment]
I could not reproduce your error on my end. I tried your URLs and the script worked.
Please look into the script's regex and compare with ntv's HTML you get when you fetch it with your browser - could be an i18n issue - and tell me what you find out - so we can fix the code.

**Comment by probonopd** [comment]
Thanks. Unfortunately I don't have any Perl skills
