### ISSUE TITLE
error in line 73 

### ISSUE THREAD

**Issue by oakcove** [isync/www-video-download#2]
hi~

I need to download a series videos of CNBC you code does help!

But error occurs in line 73, says 'video'  is not a command or program.

Is there any package need to be installed? I'm a green hand in programming. What's the problem here?

Thanks very much!

**Comment by isync** [comment]
Actually things for the CNBC script have degraded more, as the site uses a new layout since release. I looked into it and it needs more than a quick fix. Sorry. No time. This is free software, as is, no support. ...I'm afraid.
